package Exceptions;

public class main_exception {
	public static void main(String[] args) {
		try{
			System.out.println(2/0);
		}catch(ArithmeticException e){
			System.out.println("Bestia no se divide por 0 da infinito");
		}
	}

}
